version: '3'
services:
  frontend-app:
    build:
      context: ./frontend-app
    ports:
      - "4200:4200"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
